services:
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile.echoserver
    container_name: p-echo-server
    ports:
      - "9050:8000"
    restart: always
  http-server:
    build:
      context: .
      dockerfile: Dockerfile.httpserver
    container_name: p-http-server
    ports:
      - "9060:8001"
    restart: always
