services:
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile.echo-server
    container_name: p-echo-server
    ports:
      - "9050:8000"
    restart: always
  http-server:
    build:
      context: .
      dockerfile: Dockerfile.http-server
    container_name: p-http-server
    ports:
      - "9050:8001"
    restart: always
